### ISSUE TITLE
Is LinkedBrainz still active?

### ISSUE THREAD

**Issue by mongopongo** [LinkedBrainz/MusicBrainz-R2RML#8]
Looks like a dead project. Is there any actively maintained project to export MusicBrainz to RDF?

**Comment by BarryNorton** [comment]
It's been somewhat dormant due to lack of hosting, but that's recently changed - LinkedBrainz.org is moving over to a MetaBrainz server and the export was run in March and is due to run again in April

**Comment by mongopongo** [comment]
Thanks for the reply. Where do I find the RDF dumps? Also related to this, are there RDF dumps for other MetaBrainz projects as well?

**Comment by BarryNorton** [comment]
There'll be links at LinkedBrainz.org soon. I don't know of other RDF transformations, though I'm aware they'd be an interesting project (there are still more advanced relationships to map in MusicBrainz though).
